name: CI

on:
  push:
    branches: ["**"]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
    env:
      MPLBACKEND: Agg

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          # install your package + dev tools from pyproject extras
          python -m pip install -e .[dev]

      - name: Lint (ruff)
        run: python -m ruff check .

      - name: Format check (black)
        run: python -m black --check .

      - name: Tests
        run: python -m pytest -q

      # Collect artifacts on failure (handy for debugging)
      - name: Upload test artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-${{ matrix.python-version }}
          path: |
            .pytest_cache
            reports
          if-no-files-found: ignore