name: CI
on: [push, pull_request]

jobs:
  python:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install -U pip
      - run: python -m pip install -r requirements.txt
      - run: python -m pip install black ruff pytest
      - run: python -m ruff check . --output-format=github || true
      - run: python -m black --check .
      - run: python -m pytest -q

